version: '3.8'

services:
  quiz-db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: quiz_service_db
    ports:
      - "5433:5432"
    volumes:
      - quiz_db_data:/var/lib/postgresql/data

  quiz-service:
    build: .
    ports:
      - "8082:8082"
    depends_on:
      - quiz-db
    environment:
      DB_HOST: quiz-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: pass
      DB_NAME: quiz_service_db

volumes:
  quiz_db_data:
